// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pssbujriukmbhxketudh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzc2J1anJpdWttYmh4a2V0dWRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAxODg4MzUsImV4cCI6MjA5NTc2NDgzNX0.WFfz9CTgQWNXG7d7obxtaBAFyNVYbdGapn5ndLBR3Tk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});