// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcskaldqeggetwzgmvsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjc2thbGRxZWdnZXR3emdtdnNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1Mjg3MjIsImV4cCI6MjA2NTEwNDcyMn0.zYoGiXDe67F3g7PAmJthcmu3bOPRr2cOUSbXI2ov_l0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);